import { SiteImg_List } from "../../assets/Image";

export const PortfolioData = [
  {
    title: "Yurim.dev",
    imgSrc: SiteImg_List.YurimDev,
    link01: "https://github.com/xururuca9797/yurim.dev",
    link01Name: "GitHub",
    link02: "https://xururuca9797.github.io/yurim.dev",
    link02Name: "View",
    days: "2020.12.18 ~ 2020.12.25",
    purpose: "project",
    keyword: "포트폴리오 사이트",
    languageDevelopment: "React, Javascript, Styled Component, Route",
  },
  {
    title: "Eggslut",
    imgSrc: SiteImg_List.Eggslut,
    link01: "https://github.com/xururuca9797/eggslut",
    link01Name: "GitHub",
    link02: "https://xururuca9797.github.io/eggslut/",
    link02Name: "View",
    days: "2020.12.04 ~ 2020.12.04",
    purpose: "renewal",
    keyword: "반응형, 웹접근성, 크로스브라우징",
    languageDevelopment: "html5, css3, JQuery",
  },
  {
    title: "Ellesse",
    imgSrc: SiteImg_List.Ellesse,
    link01:
      "http://yurimxu.dothome.co.kr/web/ui_designguide/ellesse_wirefram.pdf",
    link01Name: "PDF",
    link02: "http://yurimxu.dothome.co.kr/web/renewal/ellesse/",
    link02Name: "View",
    days: "2020.09.08 ~ 2020.09.08",
    purpose: "renewal",
    keyword: "웹표준, 웹접근성, 크로스브라우징",
    languageDevelopment: "html5, css3, JQuery",
  },
  {
    title: "Benjerry",
    imgSrc: SiteImg_List.Benjerry,
    link01:
      "http://yurimxu.dothome.co.kr/web/ui_designguide/benjerry_wirefram.pdf",
    link01Name: "PDF",
    link02: "http://yurimxu.dothome.co.kr/web/renewal/benJerrys/",
    link02Name: "View",
    days: "2020.07.28 - 2020.07.29",
    purpose: "renewal",
    keyword: "모바일, 웹표준, 웹접근성",
    languageDevelopment: "html5, css3, JQuery",
  },
  {
    title: "Solbeach",
    imgSrc: SiteImg_List.Yangyangsolbeach,
    link01:
      "http://yurimxu.dothome.co.kr/web/ui_designguide/solbeach_designguide.pdf",
    link01Name: "PDF",
    link02: "http://yurimxu.dothome.co.kr/web/renewal/yangyang_solbeach/",
    link02Name: "View",
    days: "2020.07.16 - 2020.07.16",
    purpose: "renewal",
    keyword: "웹표준, 웹접근성",
    languageDevelopment: "html5, css3",
  },
  {
    title: "Bomapp",
    imgSrc: SiteImg_List.Bomapp,
    link01:
      "http://yurimxu.dothome.co.kr/web/ui_designguide/solbeach_designguide.pdf",
    link01Name: "PDF",
    link02: "http://yurimxu.dothome.co.kr/web/bomapp/",
    link02Name: "View",
    days: "2020.10.01 - 2020.10.01",
    purpose: "renewal",
    keyword: "웹표준, 웹접근성",
    languageDevelopment: "html5, css3, JQuery",
  },
  {
    title: "Mashup",
    imgSrc: SiteImg_List.Mashup,
    link01: "https://github.com/xururuca9797/mashup.club",
    link01Name: "GitHub",
    link02: "https://xururuca9797.github.io/mashup.club/",
    link02Name: "View",
    days: "2019.10.06 - 2019.10.07",
    purpose: "project",
    keyword: "동적효과",
    languageDevelopment: "html5, css3, Javascript",
  },
  {
    title: "Kokoa clone",
    imgSrc: SiteImg_List.Kokoa,
    link01: "https://github.com/xururuca9797/kokoa-clone",
    link01Name: "GitHub",
    link02: "https://xururuca9797.github.io/kokoa-clone/",
    link02Name: "View",
    days: "2020.11.02 - 2020.11.04",
    purpose: "markup",
    keyword: "채팅, EMD",
    languageDevelopment: "html5, css3, Javascript",
  },
  {
    title: "Naver.m",
    imgSrc: SiteImg_List.Naver,
    link01: "https://github.com/xururuca9797/naver.m",
    link01Name: "GitHub",
    link02: "https://xururuca9797.github.io/naver.m/",
    link02Name: "View",
    days: "2019.12.02 - 2019.12.02",
    purpose: "markup",
    keyword: "웹표준, 웹접근성, 모바일, 반응형",
    languageDevelopment: "html5, css3, Javascript",
  },
];
