import { SiteImg_List } from "../../assets/Image";

export const PortfolioData = [
  {
    title: "Yurim.dev",
    imgSrc: SiteImg_List.YurimDev,
    link01: "https://github.com/yunyurib/yurim.dev",
    link01Name: "GitHub",
    link02: "https://yunyurib.github.io/yurim.dev",
    link02Name: "View",
    days: "2020.12.18 ~ 2021.12.22",
    purpose: "project",
    keyword: "포트폴리오 사이트",
    languageDevelopment: "React, Javascript, Styled Component, Route",
  },
  {
    title: "Eggslut",
    imgSrc: SiteImg_List.Eggslut,
    link01: "https://github.com/yunyurib/eggslut",
    link01Name: "GitHub",
    link02: "https://yunyurib.github.io/eggslut/",
    link02Name: "View",
    days: "2020.12.04 ~ 2020.12.04",
    purpose: "project",
    keyword: "반응형, 웹접근성, 크로스브라우징",
    languageDevelopment: "html5, css3, JQuery",
  },
  {
    title: "login_api",
    imgSrc: SiteImg_List.LoginApi,
    link01: "https://github.com/yunyurib/login_api",
    link01Name: "GitHub",
    link02: "https://yunyurib.github.io/login_api/signin.html",
    link02Name: "View",
    days: "2021.02.01 ~ 2021.02.05",
    purpose: "project",
    keyword: "로그인API",
    languageDevelopment: "html5, css3, Javascript, API",
  },
  {
    title: "Mashup",
    imgSrc: SiteImg_List.Mashup,
    link01: "https://github.com/yunyurib/mashup.club",
    link01Name: "GitHub",
    link02: "https://yunyurib.github.io/mashup.club/",
    link02Name: "View",
    days: "2019.10.06 - 2019.10.07",
    purpose: "project",
    keyword: "동적효과",
    languageDevelopment: "html5, css3, Javascript",
  },
  {
    title: "Kokoa clone",
    imgSrc: SiteImg_List.Kokoa,
    link01: "https://github.com/yunyurib/kokoa-clone",
    link01Name: "GitHub",
    link02: "https://yunyurib.github.io/kokoa-clone/",
    link02Name: "View",
    days: "2020.11.02 - 2020.11.04",
    purpose: "markup",
    keyword: "채팅, EMD",
    languageDevelopment: "html5, css3, Javascript",
  },
  {
    title: "Naver.m",
    imgSrc: SiteImg_List.Naver,
    link01: "https://github.com/yunyurib/naver.m",
    link01Name: "GitHub",
    link02: "https://yunyurib.github.io/naver.m/",
    link02Name: "View",
    days: "2019.12.02 - 2019.12.02",
    purpose: "markup",
    keyword: "웹표준, 웹접근성, 모바일, 반응형",
    languageDevelopment: "html5, css3, Javascript",
  },
];
